name: Koncur Repo CI testing

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  run-kantra-test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download and install kantra
        run: |
          podman cp $(podman create --name kantra-download quay.io/konveyor/kantra:latest):/usr/local/bin/kantra . &&\
          podman rm kantra-download
          cp kantra /usr/local/bin/kantra

      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Build Koncur
        run: |
          go build -o /usr/local/bin/koncur ./cmd/koncur/main.go

      # This should create a maven settings file with the github server's set up and the user/pass set to the github token.
      - name: Create maven settings file
        uses: s4u/maven-settings-action@v4.0.0
        with:
          path: settings.xml
      
      - name: Create kantra config
        run: |
          mkdir -p .koncur/config
          cat <<EOF > target-kantra.yaml
          type: kantra
          kantra:
          \tmavenSettings: $(pwd)/settings.xml
          EOF
      
      - name: Run test
        run: |
          koncur run tests -t kantra

#  run-tackle2-hub-test:
