name: Koncur Repo CI testing

permissions:
  checks: write

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

env:
  RUNNER_IMG: quay.io/konveyor/kantra:latest
  JAVA_PROVIDER_IMG: quay.io/konveyor/java-external-provider
  GENERIC_PROVIDER_IMG: quay.io/konveyor/generic_external_provider
  CSHARP_PROVIDER_IMG: quay.io/konveyor/c-sharp-provider
jobs:
  run-kantra-test:
    strategy:
      fail-fast: false
      matrix:
        # Using macos to test amd64 and ubuntu to test arm
        # THis is because you can't use container's on mac os arm runners.
        os: [macos-15-intel, ubuntu-24.04-arm, windows-latest]
    uses: ./.github/workflows/kantra.yaml
    with:
      os: ${{ matrix.os }}


#  run-tackle2-hub-test:
