name: Koncur Test with kantra

on:
  workflow_call:
    inputs:
      os:
        description: os to run on 
        required: true 
        type: string

jobs:
  kantra-test:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Verify local/bin is on the path
        run: |
          mkdir -p $HOME/.local/bin
          echo $HOME/.local/bin >> $GITHUB_PATH

      - name: Install podman
        if: ${{ inputs.os == 'macos-15-intel' }}
        run: |
          brew install podman
          podman machine init --rootful
          podman machine start
          podman cp $(podman create --name kantra-download quay.io/konveyor/kantra:latest):/usr/local/bin/darwin-kantra . &&\
          podman rm kantra-download
          cp kantra $HOME/.local/bin/kantra

      - name: Download and install kantra
        if: ${{ inputs.os != 'macos-15-intel' }}
        run: |
          podman cp $(podman create --name kantra-download quay.io/konveyor/kantra:latest):/usr/local/bin/kantra . &&\
          podman rm kantra-download
          cp kantra $HOME/.local/bin/kantra

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Build Koncur
        run: |
          go build -o $HOME/.local/bin/koncur ./cmd/koncur/main.go

      # This should create a maven settings file with the github server's set up and the user/pass set to the github token.
      - name: Create maven settings file
        uses: s4u/maven-settings-action@v4.0.0
        with:
          path: "${{ runner.temp }}/settings.xml"
      
      - name: Create kantra config
        run: |
          mkdir -p .koncur/config
          cat <<-EOF > .koncur/config/target-kantra.yaml
          type: kantra
          kantra:
            mavenSettings: ${{ runner.temp }}/settings.xml
          EOF
      
      - name: Run test
        run: |
          koncur run tests -t kantra 
